config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'orderd_products/update'
  end
  devise_for :admins
  devise_for :customers


root to: 'customers#top'
get '/products_genre/:id' => 'products#genre',as:'product_genre'
get 'congfirm' => 'customers#confirm'
get 'orders/thanks' => 'orders#thanks'
delete "/cart" => "carts#destroy_all",as:"carts_destroy_all"
#customerのルーティング
resources :addresses
resources :carts
resources :products

resources :orders do
  post :confirm, action: :confirm_new, on: :new
  end

resources :customers, only: [:show, :edit, :update, :destroy]

  namespace :admin do
    get '/orders/all' => 'orders#all', as: 'orders_all'
    resources :products, only: [:show, :index, :edit, :update, :new, :create]
    resources :genres, only: [:index, :create, :edit, :update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  # admin/orderのルート設定
   namespace :admin do
    get '/orders/top'
   resources :orders, only: [:index, :show, :update]
   resources :customers, only: [:index, :show, :edit, :update]
   resources :orderd_products, only: [:update]
end

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :orderd_products
  belongs_to :customer
  enum order_status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }
  enum method_of_payment: { クレジットカード: 'card', 銀行振込: 'bank' }
  validates :postcode, presence: true
  validates :shipping_address, presence: true
  validates :shipping_name, presence: true

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!


  def top
    @count = Order.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).count

  end

  def all
    @orders_all = Order.page(params[:page]).order(created_at: :desc)
  end

  def index

    @path = Rails.application.routes.recognize_path(request.referer)

    if @path[:action] == "top"
      @orders = Order.page(params[:page]).order(created_at: :desc).where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)

    elsif @path[:action] == "show"
      @customer = Customer.find(@path[:id])
      @orders = @customer.orders.page(params[:page]).order(created_at: :desc)
    end
  end

  def show
    @order = Order.find(params[:id])
    @orderd_products = @order.orderd_products
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    # binding.pry
    if @order.order_status == "入金確認"
      @order.orderd_products.update(making_status: 1)
    end
    redirect_to admin_order_path(@order.id)
  end

  private

  def order_params
    params.require(:order).permit(:customer_id, :total_amount, :order_status, :method_of_payment, :postcode, :shipping_address, :shipping_name, :postage)
  end

  def set_zone
    Time.zone='Tokyo'
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def new
    @customer = current_customer
    @order = Order.new
    @address = Address.new
    @order.orderd_products.build
  end

  def index
    @customer = current_customer
    @orders = Order.all

  end

  def create
    @order = current_customer.orders.new(order_params)
    @carts = current_customer.cart_items
    @order_postage = 800
    @sum = 0
      @carts.each do |c|
        price = c.product.price
        qty = c.quantity
        @sum +=  (price * 1.08) * qty
        #binding.pry
      end
    @total_amount = @sum + @order_postage
    #@total_amount =
    #binding.pry
    @order.attributes = {total_amount: @total_amount}
    @order.save
    @carts = current_customer.cart_items
      @carts.each do |c|
      orderd_product = OrderdProduct.new
      # orderd_productに必要なカラムを入れる
        orderd_product.product_id = c.product_id
        orderd_product.quantity = c.quantity
        orderd_product.price = c.product.price
        orderd_product.order_id = @order.id
        orderd_product.save!
      end
    @carts.destroy_all
    # binding.pry

    redirect_to orders_thanks_path

  end

  def confirm_new

    @customer = current_customer
    @order = @customer.orders.new(order_params)
    @carts = current_customer.cart_items

    @address = Address.new(
      customer_id: current_customer.id,
      post_code: params[:order][:address][:post_code],
      shipping_address: params[:order][:address][:shipping_address],
      shipping_name: params[:order][:address][:shipping_name]
    )

    if params[:select_shipping_address] == "1"
     @order.shipping_address = @customer.address
     @order.postcode = @customer.post_code
     @order.shipping_name = @customer.total_name
   elsif params[:select_shipping_address] == "2"
     @order.shipping_address = params[:order][:shipping_address]
     @select = Address.find_by(shipping_address: params[:order][:shipping_address])
     if @select
      @order.postcode = @select[:post_code]
      @order.shipping_name = @select[:shipping_name]
    else
      flash[:notice] = "届け先を選択してください"
      render :new
     end
   elsif params[:select_shipping_address] == "3"
     @order.shipping_address = @address.shipping_address
     @order.postcode = @address.post_code
     @order.shipping_name = @address.shipping_name
     @address.save
     render :new unless @address.valid?
   end


   @order_postage = 800
   # binding.pry
   end

  def show
    @customer = current_customer
    @order = Order.find(params[:id])
    @order_postage = 800
    @orderd_products = @order.orderd_products
    @item = OrderdProduct.all
    #@orderd_product = OrderdProduct.sum(:price)
  end



  def edit
  end

  def thanks
    @customer = current_customer
  end

  private

  def order_params
    params.require(:order).permit(:user_id, :total_amount, :order_status, :method_of_payment, :postcode, :shipping_address, :shipping_name, :postage, orderd_products_attributes: [:price])
  end

  # def orderd_product_params
  #   params.require(:orderd_product).permit(:quantity, :price, :making_status, :order_id, :product_id)
  # end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/all.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-10 p-6">
      <h1>注文一覧画面</h1>
      <table class="table">
        <thead>
          <tr class="active">
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>

        <tbody>
          <% @orders_all.each do |order| %>
          <tr>
            <td><%= link_to order.created_at.strftime("%Y年%m月%d日%H時%M分%S秒 "), admin_order_path(order.id) %></td>
            <td><%= order.customer.family_name %><%= order.customer.last_name %></td>
              <% sum = 0 %>
              <% order.orderd_products.each do |orderd_product| %>
              <% sum += orderd_product.quantity %>
              <% end %>
              <% @total_quatity = sum %>
             <td><%= @total_quatity %></td>
            <td><%= order.order_status %></td>
          </tr>
          <% end %>
        </tbody>

      </table>
    </div>
  </div>
  <%= paginate @orders_all, class: "paginate" %>
</div>

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-10 p-6">
      <h1>注文一覧画面</h1>
      <table class="table">
        <thead>
          <tr class="active">
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>

        <tbody>
          <% @orders.each do |order| %>
          <tr>
            <td><%= link_to order.created_at.strftime("%Y年%m月%d日%H時%M分%S秒 "), admin_order_path(order.id) %></td>
            <td><%= order.customer.family_name %><%= order.customer.last_name %></td>
              <% sum = 0 %>
              <% order.orderd_products.each do |orderd_product| %>
              <% sum += orderd_product.quantity %>
              <% end %>
              <% @total_quatity = sum %>
             <td><%= @total_quatity %></td>
            <td><%= order.order_status %></td>
          </tr>
          <% end %>
        </tbody>

      </table>
    </div>
  </div>
  <%= paginate @orders, class: "paginate" %>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <h3>注文詳細画面</h3>
    <div class="col-xs-4 col-xs-offset-1">
      <table class="table table-noborder">
        <tbody>
          <tr>
            <th>購入者</th>
            <td>
              <%= link_to admin_customer_path(@order.customer) do %>
              <%= @order.customer.family_name %>　<%= @order.customer.last_name %>
              <% end %>
            </td>

          </tr>
          <tr>
            <th>配送先</th>
            <td>〒<%= @order.postcode %> <%= @order.shipping_address %><br>
              <%= @order.shipping_name %></td>
            </tr>
            <tr>
              <th>支払方法</th>
              <td><%= @order.method_of_payment %></td>
            </tr>
            <tr>
              <th>注文ステータス</th>
              <%= form_for @order, :url => {:controller => :orders, :action => :update} do |o| %>
              <td><%= o.select :order_status, Order.order_statuses.keys %>
                <%= o.submit "更新",class: "btn btn-info"%></td>
                <% end %>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-6 col-xs-offset-1">
          <table class="table">
            <thead>
              <tr  class="warning">
                <th>商品名</th>
                <th>単価（税込）</th>
                <th>数量</th>
                <th>小計</th>
                <th>製作ステータス</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
             <% @order.orderd_products.each do |orderd_products| %>
             <tr>
              <th><%= orderd_products.product.name %></th>
              <th><%= (orderd_products.price * 1.08).floor.to_s(:delimited, delimiter: ',') %></th>
              <th><%= orderd_products.quantity %></th>
              <th><%= ((orderd_products.price * 1.08) * orderd_products.quantity).floor.to_s(:delimited, delimiter: ',') %></th>
              <%= form_for orderd_products, url:"/admin/orderd_products/#{orderd_products.id}" do |item| %>
              <th><%= item.select :making_status, OrderdProduct.making_statuses.keys %></th>
              <th><%= item.submit "更新",class: "btn btn-info" %></th>
              <% end %>
            </tr>
            <% end %>

          </tbody>
        </table>
      </div>

      <div class="col-xs-4">
        <table class="table table-noborder">
          <tbody>
            <% @sum = 0 %>
            <% @orderd_products.each do |o_product| %>
            <tr>
              <% @sum += (o_product.product.price * 1.08) * o_product.quantity %>
              <% end %><br><th>商品合計</th>
              <td><%= (@sum).floor.to_s(:delimited, delimiter: ',') %>円</td>
            </tr>
            <tr>
              <th>送料</th>
              <td><%= @order.postage %>円</td>
            </tr>
            <tr>
              <th>請求金額合計</th>
              <th><%= @order.total_amount.to_s(:delimited, delimiter: ',') %>円</th>
            </tr>


          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/top.html.erb
<div class="container">
	<div class="row">
		<h2>管理者画面</h2>
		<p style="font-size:1.5em;">本日の注文数　　　<%= link_to @count, admin_orders_path %>件</p>
	</div>
</div>