config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'orderd_products/update'
  end
  devise_for :admins
  devise_for :customers


root to: 'customers#top'
get '/products_genre/:id' => 'products#genre',as:'product_genre'
get 'congfirm' => 'customers#confirm'
get 'orders/thanks' => 'orders#thanks'
delete "/cart" => "carts#destroy_all",as:"carts_destroy_all"
#customerのルーティング
resources :addresses
resources :carts
resources :products

resources :orders do
  post :confirm, action: :confirm_new, on: :new
  end

resources :customers, only: [:show, :edit, :update, :destroy]

  namespace :admin do
    get '/orders/all' => 'orders#all', as: 'orders_all'
    resources :products, only: [:show, :index, :edit, :update, :new, :create]
    resources :genres, only: [:index, :create, :edit, :update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  # admin/orderのルート設定
   namespace :admin do
    get '/orders/top'
   resources :orders, only: [:index, :show, :update]
   resources :customers, only: [:index, :show, :edit, :update]
   resources :orderd_products, only: [:update]
end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  def total_name
  family_name + last_name
  end

  def active_for_authentication?
   super && (self.is_deleted == false)
 end

 enum status: { 有効: false, 退会: true }
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
  end

  private

  def customer_params
      params.require(:customer).permit(:family_name, :last_name, :family_name_kana, :last_name_kana, :post_code, :address, :telephone_number, :email, :is_deleted)
  end

end

app/controllers/customer/customers_controller.rb
class CustomersController < ApplicationController
  def top
  	@customer = current_customer
  end

  def show
  	@customer = Customer.find(params[:id])
  end

  def edit

  end

  def confirm
  end

  private
  def customer_params
    params.require(:user).permit(:family_name,:last_name,:family_name_kana,:last_name_kana,:post_code,:post_code,:telephone_number)
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def top
    @customer = current_customer#ヘッダー
    @genres = Genre.where(is_active: true)
    #ジャンルサイドバー一覧
    genres = []
    @genres.each do |genre|
     genres << genre.id
    end#ジャンルのidを[]に入れておく、下の行でそれを使う

    @products = Product.where(sales_status: 0,genre_id: genres).page(params[:page]).reverse_order#productテーブルから全て取り出す,kaminari
    @count = Product.where(sales_status: 0,genre_id: genres).count#product内全件の数
    @title = "商品一覧"#genre_id(params)がない時の一覧タイトル

    #@products = Product.page(params[:page]).reverse_order#kaminariページャ用のため同じ名前
  end

  def show
    @customer = current_customer#customerのidを取得
  end

  def edit
    @customer = Customer.find(params[:id])#customerのidを取得
  end
  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to customer_path
  end

  def confirm
    @customer = current_customer
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  def logout
    session[:customer_id] = nil
    redirect_to root_path
  end

  private
  def customer_params
    params.require(:customer).permit(:family_name,:last_name,:family_name_kana,:last_name_kana,:post_code,:address,:telephone_number,:is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
	def log_in(customer)
    	session[:customer_id] = customer.id
	end
	def log_out
		session.delete(:customer_id)
		@customer = nil
	end
end

app/views/customers/confirm.html.erb
<div class="container">
	<div class="row">
		<div class="taikai col-xs-5 col-xs-offset-3 text-center">
			<br>
			<br>
			<br>
		<p class="font-weight-bold"><span style="font-size:1.6em;">本当に退会しますか？</span></p>
		<p>退会すると、会員登録情報や<br>
			これまでの購入履歴が閲覧できなくなります。<br>
		退会する場合は、「退会する」をクリックしてください。</p><br>


		<%=link_to "退会しない", customer_path(@customer),class: "btn btn-info" %>
		<%=link_to "退会する", customer_path(@customer.id),method: :delete,class: "btn btn-danger" %>
		</div>
	</div>
</div>

app/views/customers/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-9 col-xs-offset-1">
			<h3>登録情報編集<%= link_to "退会する", congfirm_path , class: "btn btn-danger" %></h3>
			<%= form_for(@customer) do |f| %>
			<table class="table table-bordered">
				<tr>
					<th class="warning">氏名</th>
					<td>
						<div class="field">
							<%= f.text_field :family_name, autofocus: true, autocomplete: "family_name" %>
							<%= f.text_field :last_name, autofocus: true, autocomplete: "last_name" %>
						</div>
					</td>
				</tr>

				<tr>
					<th class="warning">カナ</th>
					<td>
						<div class="field">
							<%= f.text_field :family_name_kana, autofocus: true, autocomplete: "family_name_kana" %>
							<%= f.text_field :last_name_kana, autofocus: true, autocomplete: "last_name_kana" %>
						</div>
					</td>
				</tr>

				<tr>
					<th class="warning">郵便番号</th>
					<td>
						<div class="field">
							<%= f.text_field :post_code, autofocus: true, autocomplete: "post_code" %>
						</div>
					</td>
				</tr>

				<tr>
					<th class="warning">住所</th>
					<td>
						<div class="field">
							<%= f.text_field :address, autofocus: true, autocomplete: "address",:size => "60*30" %>
						</div>
					</td>
				</tr>

				<tr>
					<th class="warning">電話番号</th>
					<td>
						<div class="field">
							<%= f.text_field :telephone_number, autofocus: true, autocomplete: "telephone_number" %>
						</div>
					</td>
				</tr>

				<tr>
					<th class="warning">メールアドレス</th>
					<td>
						<div class="field">
							<%= f.email_field :email, autofocus: true, autocomplete: "email",:size => "50*30" %>
						</div>
					</td>
				</tr>
			</table>
		</div>
		<div class="row">
			<div class="actions col-xs-2 col-xs-offset-9">
				<%= f.submit "編集内容を保存する", class: "btn btn-info" %>
			</div>
			<% end %>
		</div>
	</div>
</div>

app/views/customers/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-5 col-xs-offset-1">
			<h4>マイページ</h4>
			<p><span style="font-size:1.3em;">登録情報</span>
				&nbsp;&nbsp;<%= link_to '編集する', edit_customer_path(@customer), class: "btn btn-info" %>
				&nbsp;&nbsp;<%= link_to 'パスワードを編集する', edit_customer_registration_path, class: "btn btn-info" %>
			</p>
		</div>
		<div class="col-xs-6 col-xs-offset-1">
			<table class="table table-bordered">
				<tr>
					<th class="warning">氏名</th>
					<td><%= @customer.family_name %>&nbsp; <%= @customer.last_name %></td>
				</tr>
				<tr>
					<th class="warning">カナ</th>
					<td><%= @customer.family_name_kana %>&nbsp; <%= @customer.last_name_kana %></td>
				</tr>
				<tr>
					<th class="warning">郵便番号</th>
					<td>〒<%= @customer.post_code.to_s.insert(3, "-") %></td>
				</tr>
				<tr>
					<th class="warning">住所</th>
					<td><%= @customer.address %></td>
				</tr>
				<tr>
					<th class="warning">電話番号</th>
					<td><%= @customer.telephone_number %></td>
				</tr>
				<tr>
					<th class="warning">メールアドレス</th>
					<td><%= @customer.email %></td>
				</tr>
			</table>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-5 col-xs-offset-1">
			<p><span style="font-size:1.1em;">配送先</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to '一覧を見る', addresses_path(@customer), class: "btn btn-warning" %>&nbsp;&nbsp;
				<span style="font-size:1.1em;">注文履歴</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to '一覧を見る', orders_path(@customer), class: "btn btn-warning" %></p>
			</div>
		</div>
	</div>
</div>

app/views/customers/top.html.erb
<div class="container">
  <p><%= flash[:notice] %></p>
  <div class="row">
      <div class="col-xs-2">
      <%= render 'layouts/sidegenre', genres: @genres %>
      </div>
       <div class="col-xs-10">
        <p><h2><%= @title %><span style="font-size:0.7em;">全<%= @count %>件</span></h2><!-- 商品一覧、ジャンルの商品件数-->
        <div class="row">
          <% @products.each do |product| %><!--商品一覧-->
          <div class="col-xs-3">
            <%= link_to product_path(product.id) do %><!--画像〜値段クリックで詳細画面へ-->
              <%= attachment_image_tag product, :image,size: "220x170" %><br><!--商品画像-->
              	<%= product.name %><br>
              ￥<%= (product.price * 1.08).floor.to_s(:delimited, delimiter: ',') %><br><!--商品税込み価格,小数点切り捨て-->
            <% end %>
           </div>
          <% end %>
        </div>
        <div class ="text-center">
       <%= paginate(@products) %>
       </div>
  </div>
  </div>
</div>