config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'orderd_products/update'
  end
  devise_for :admins
  devise_for :customers


root to: 'customers#top'
get '/products_genre/:id' => 'products#genre',as:'product_genre'
get 'congfirm' => 'customers#confirm'
get 'orders/thanks' => 'orders#thanks'
delete "/cart" => "carts#destroy_all",as:"carts_destroy_all"
#customerのルーティング
resources :addresses
resources :carts
resources :products

resources :orders do
  post :confirm, action: :confirm_new, on: :new
  end

resources :customers, only: [:show, :edit, :update, :destroy]

  namespace :admin do
    get '/orders/all' => 'orders#all', as: 'orders_all'
    resources :products, only: [:show, :index, :edit, :update, :new, :create]
    resources :genres, only: [:index, :create, :edit, :update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  # admin/orderのルート設定
   namespace :admin do
    get '/orders/top'
   resources :orders, only: [:index, :show, :update]
   resources :customers, only: [:index, :show, :edit, :update]
   resources :orderd_products, only: [:update]
end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
before_action :authenticate_customer!, only: [:index, :update, :destroy, :destroy_all]#ログインしていない人をログイン画面へ
  def index
  	@customer = current_customer#ヘッダー
  	@cart_items =CartItem.all#cart_itemsテーブルから全て取り出す
  end

  def update
    cart_item = CartItem.find(params[:id])

    cart_item.update(cart_params)
    redirect_to carts_path#カート内一覧
  end
  def destroy
    cart_item = CartItem.find(params[:id])
    cart_item.destroy#データ（レコード）を削除
    redirect_to carts_path#カート内一覧
  end
  def destroy_all#ルーティング追加予定
    #本来はモデル.find().アソシエーションだけど
    #ログインしてる人のidが欲しいので、deviceで自動定義してくれるcurrent_customerを使う、customerに紐づくカーとを消す処理
    current_customer.cart_items.destroy_all
    redirect_to carts_path#カート内一覧
  end

  def show
  end

  def new
  end
#カートに商品を入れる
  def create
    @product = Product.find(params[:cart_item][:product_id] )

    if current_customer != nil
      if @product.in_cart?(current_customer)
         @cart_item = current_customer.cart_items.find_by(product_id: @product.id)
         @cart_item.quantity += params[:cart_item][:quantity].to_i
         @cart_item.save

      else
  	   @cart = CartItem.new(cart_params)#新規投稿
       @cart.customer_id = current_customer.id
       @cart.save#保存

     end
       redirect_to carts_path#カート内一覧

    else
     flash[:notice] = "ログインをして下さい"#ログインを促す
     redirect_to customer_session_path#カスタマーのsign_in画面へ

     end
  end

private
    def cart_params
        params.require(:cart_item).permit(:customer_id, :product_id, :quantity)
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/edit.html.erb
<h1>Carts#edit</h1>
<p>Find me in app/views/carts/edit.html.erb</p>

app/views/carts/index.html.erb
<!--配送先一覧-->
<div class="container">
    <div class="row">
        <span style="font-size:1.6em;">ショッピングカート</span>
        <span class="pull-right"><%= link_to "カートを空にする", carts_destroy_all_path, method: :delete,class: "btn btn-warning" %></span>
        <div class="col-xs-12">
        </div>
        <div class="col-xs-10 col-xs-offset-1">
            <table class="table table-bordered">
                <thead>
                    <tr class="warning">
                        <th>商品名</th><th>単価（税込）</th><th>数量</th><th>小計</th><th></th>
                    </tr><!--見出し-->
                </thead>
                <tbody>
                    <% array = [] %><!--空の配列を用意-->
                    <% @customer.cart_items.each do |cart_item| %>
                    <tr>
                        <td><!--商品名-->
                            <%= attachment_image_tag cart_item.product, :image,:fill, 100, 50 %>
                            <%= cart_item.product.name %>
                        </td>
                        <td><%= (cart_item.product.price * 1.08).floor.to_s(:delimited, delimiter: ',') %></td><!--単価(税込み)-->
                        <td>
                            <%= form_for cart_item, url:"/carts/#{cart_item.id}" do |f| %><!--繰り返しのcart_itemを使って繰り返し取り出す-->
                            <%= f.text_field :quantity,:size => "5*30" %>
                            <%= f.submit '変更する',class: "btn btn-info" %>
                            <% end %>
                        </td>
                        <td class="text-center align-middle"><!--小計-->
                            <%= (cart_item.product.price * 1.08 *  cart_item.quantity).floor.to_s(:delimited, delimiter: ',') %>
                        </td>
                        <td>
                            <%= link_to "削除する", "/carts/#{cart_item.id}", method: :delete,class: "btn btn-warning" %><!--繰り返しの<cart_itemを使って繰り返し取り出す-->
                        </td>
                        <% array << cart_item.product.price * cart_item.quantity %><!--#bookテーブルのレコードを１件ずつ取り出す繰り返しのたびに、計算した値を配列に入れる-->
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-2 col-xs-offset-1">
            <%=link_to "買い物を続ける",products_path,class: "btn btn-info" %><!--買い物を続けるリンク-->
        </div>

        <div class="col-xs-2 col-xs-offset-6">
            <table class="table table-bordered margin-0">
                <tbody class="thead-lignt">
                    <tr>
                        <td class="warning">合計金額</td>
                        <td>
                            <%= (array.sum * 1.08).floor.to_s(:delimited, delimiter: ',') %><!--合計金額の文字必要、上の繰り返しでとった値を合計して税金計算、小数点以下切り捨て-->
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-5 col-xs-offset-5">
            <% if @customer.cart_items.exists? %>
                <%= link_to"情報入力に進む",new_order_path,class: "btn btn-info btn-lg"  %>
            <% end %>
        </div>

app/views/carts/new.html.erb
<h1>Carts#new</h1>
<p>Find me in app/views/carts/new.html.erb</p>

app/views/carts/show.html.erb
<h1>Carts#show</h1>
<p>Find me in app/views/carts/show.html.erb</p>